name: MusicService
version: 1.4.3
description: Provides the ability to stream music.
author: Palisade
website: http://dev.bukkit.org/server-mods/musicservice-play-music-anywhere/

main: blakesteel.MusicService.MusicService
database: false
softdepend: [WorldGuard, Factions, Towny]

commands:
  setmusic:
    description: Set the music URL at the land at this location.
    permission: musicservice.setmusic
    usage: Type /<command> to set the music URL at this location.
  reloadmusic:
    description: Reload the music at this location.
    permission: musicservice.reloadmusic
    usage: Type /<command> to reload the music at this location.
  pickmusic:
    description: Pick the music stream produced by the findmusic command.
    permission: musicservice.setmusic
    usage: Type /<command> # to pick the music stream at this location from the findmusic command.
  findmusic:
    description: Find music streams on shoutcast by searching.
    permission: musicservice.findmusic
    usage: Type /<command> searchstring to find streams on the shoutcast website.

permissions:
  musicservice.*:
    description: Supports setting of the music stations.
    children:
      musicservice.setmusic: true
      musicservice.reloadmusic: true
      musicservice.pickmusic: true
      musicservice.findmusic: true
  musicservice.setmusic:
    description: Set the music URL for this location.
    default: true
  musicservice.reloadmusic:
    description: Reload the music at this location.
    default: true
  musicservice.pickmusic:
    description: Pick the music stream produced by the findmusic command.
    default: true
  musicservice.findmusic:
    description: Find music streams on shoutcast by searching.
    default: true