name: MusicService
version: 1.4.9
description: Provides the ability to stream music.
author: Palisade
website: http://dev.bukkit.org/server-mods/musicservice-play-music-anywhere/

main: blakesteel.MusicService.MusicService
database: false
softdepend: [WorldGuard, Factions, Towny, Regios, iZone]

commands:
  musicservice:
    description: Find music streams by searching radio station sites.
    usage: Type /<command> to get list of available MusicService commands.
    aliases: [music, ms]
    
permissions:
  musicservice.*:
    description: Supports setting of the music stations.
    children:
      musicservice.setshout: true
      musicservice.setice: true
      musicservice.reload: true
      musicservice.pick: true
      musicservice.findshout: true
      musicservice.findice: true
  musicservice.setshout:
    description: Set the music shoutcast URL for this location.
    default: op
  musicservice.setice:
    description: Set the music icecast URL for this location.
    default: op
  musicservice.reload:
    description: Reload the music at this location.
    default: op
  musicservice.pick:
    description: Pick the music stream produced by the findmusic command.
    default: op
  musicservice.findshout:
    description: Find music streams on shoutcast by searching.
    default: op
  musicservice.findice:
    description: Find music streams on icecast by searching.
    default: op
